version: "3.8"

services:
  postgres-customer:
    container_name: postgres-customer
    image: postgres:16
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-customer
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres-customer

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: